features/urls.py
from django.urls import path
from django.contrib import admin

from features import views

home/urls.py
from django.contrib import admin
from django.urls import path,include
import features
from . import views
app_name='home'
urlpatterns = [
    path('',views.home,name="hom" ),
     path('search/',features.views.search),
    path('search/trains',features.views.getTrains),
    path('schedule/',features.views.schedule),
    path('schedule/trains',features.views.getTinfo),
    path('pnr/',features.views.pnr,name="pnr"),
    #path('logout/',views.logout ),
    ]

rail/urls.py
from django.contrib import admin
from django.urls import path,include
from features import views
from home import views
app_name='basic'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace="home"),name="home"),
    #path('',views.log,name='log'),
    #path('register/',views.Reg,name="reg"),
    #path('logout/',views.logout,name="logout"),

]

features/models.py
from django.db import models

# Create your models here.
class Members(models.Model):
    username=models.CharField(max_length=250)
    password=models.CharField(max_length=16)
    email=models.CharField(max_length=250)
    number=models.CharField(max_length=10)

    def __str__(self):
        return self.username

home/models.py
from django.db import models

# Create your models here.
class Trains(models.Model):
    tno=models.CharField(primary_key=True,max_length=50)
    tname=models.CharField(max_length=50)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)

    def __str__(self):
        return self.tno

class Route(models.Model):
    rid=models.CharField(max_length=50)
    ostation=models.CharField(max_length=50)
    dstation=models.CharField(max_length=50)
    def __str__(self):
        return self.rid

class Station(models.Model):
    sid=models.CharField(primary_key=True,max_length=50)
    sname=models.CharField(max_length=50)
    def __str__(self):
        return self.sid


class RouteStation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    sid=models.ForeignKey('Station',on_delete=models.CASCADE)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)
    order=models.IntegerField()
    atime=models.CharField(max_length=50)

class Reservation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    user=models.CharField(max_length=50)
    nos=models.IntegerField()
    date=models.CharField(max_length=50)
    amt=models.IntegerField()
    cls=models.CharField(max_length=50)
    status=models.CharField(max_length=50)
    pnr=models.CharField(max_length=50)
    src=models.CharField(max_length=50)
    des=models.CharField(max_length=50)

class Add_Train(models.Model):
    sname = models.CharField(max_length=30,null=True)
    tno = models.IntegerField(null=True)
    ostation = models.CharField(max_length=30,null=True)
    dstation = models.CharField(max_length=30,null=True)
    departuretime=models.CharField(max_length=30,null=True)
    arrivaltime=models.CharField(max_length=30,null=True)
    def __str__(self):
        return self.sname+" "+str(self.tno)

features/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class Usearch(forms.Form):
    src=forms.CharField(max_length=50)
    des = forms.CharField(max_length=50)

class Trsc(forms.Form):
    tnum=forms.IntegerField()

class AddR(forms.Form):
    rid=forms.CharField(max_length=50)
    ostation=forms.CharField(max_length=50)
    dstation=forms.CharField(max_length=50)

class AddST(forms.Form):
    sid=forms.CharField(max_length=50)
    sname=forms.CharField(max_length=50)

class AddT(forms.Form):
    rid=forms.CharField(max_length=50)
    tno=forms.CharField(max_length=50)
    tname=forms.CharField(max_length=50)

class AddRT(forms.Form):
    tno=forms.CharField(max_length=50)
    sid= forms.CharField(max_length=50)
    rid=forms.CharField(max_length=50)
    order=forms.IntegerField()
    atime=forms.CharField(max_length=50)

class Pnr(forms.Form):
    pnr=forms.CharField(max_length=50)

#class Book(forms.Form):
 #   cls=forms.CharField(max_length=10)
  #  dt=forms.CharField(max_length=10)

home/forms.py
#from django.contrib.auth.models import User
#from django.contrib.auth.forms import UserCreationForm
#from django import forms

#class UserLogin(forms.Form):
 #   username = forms.CharField(max_length=250)
  #  password = forms.CharField(max_length=16, widget=forms.PasswordInput())


#class UserReg(forms.ModelForm):
 #   number=forms.CharField(required=True)
  #  class Meta:
   #     model=User
    #    fields=['username','password','email','number']

    #def save(self, commit=True):
     #   user = super(UserReg, self).save(commit=False)
      #  user.number = self.cleaned_data["number"]
       # if commit:
        #    user.save()
        #return user

features/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.db.models import Max
from django.template import loader
from .models import Members
from .forms import Trsc,Usearch,AddR,AddST,AddT,AddRT
import json

from home.models import RouteStation,Station,Route,Trains,Reservation,Add_Train
def getTrains(request):
    if request.method=='POST':
        form=Usearch(request.POST)
        if form.is_valid():

            data=form.cleaned_data
            src=data['src']
            des=data['des']
            a=RouteStation.objects.filter(sid=des)
            x=[]
            o=0
            for i in a:
                tno=i.tno
                b=RouteStation.objects.filter(tno=tno,sid=src)
                for j in b:
                    if j.order<i.order:
                        x.append(j)
                        o=i.order-j.order

        else:
            return HttpResponse('<h1>invalid Data</h1>')
        return render(request,'features/trains.html',{'data':x,'o':o,'src':src,'des':des})
    return HttpResponse('<h1>Wrong REq</h1>')


def schedule(request):
    a=Trains.objects.all()
    return render(request,'features/schedule.html',{'a':a})

def getTinfo(request):
    form=Trsc(request.GET)
    if form.is_valid():
        data=form.cleaned_data
        tno=data['tnum']
        a=RouteStation.objects.filter(tno=tno).order_by('order')


        return render(request,'features/trinfo.html',{'data':a})

    return HttpResponse('<h1>DAta invalid<h1>')

def search(request):
    a=Station.objects.all()
    return render(request,'features/seat.html',{'a':a})


def pnr(request):
    if request.method=='POST':
        pnr=request.POST['pnr']
        a=Reservation.objects.filter(pnr=pnr)

        return render(request,'features/pnr.html',{'r':a})


    return render(request,'features/pnr.html')

home/views.py
from django.shortcuts import render
from django.template import loader
from features.models import Members
#from .forms import UserLogin,UserReg
from django.contrib import auth
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Create your views here.
def home(request):
    return render(request,'features/home.html')

features/templates/features/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Railway System</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">


    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <style>
        body{
            background-image:url('{% static "images/hompage.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;
        }
        .sty
        {
            font-family: 'Dancing Script', cursive;
            color:white;
        }
        .row1{




            background-color:rgba(0,0,0,0.6);


        }
    </style>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

features/templates/features/home.html
{% extends 'features/base.html' %}

{% block body %}
<!DOCTYPE html>
<html>
<head>
<title>Railway Enquiry System</title>
</head>
{% load static %}
<style>
body{

     background-image:url('{%static "images/pic.jpeg" %}');
}
h1{
    text-align: center;
    font-size: 42px;
    font-family: Arial, Helvetica, sans-serif;
    color: brown;
}
.left input[type=submit]{
    background-color: rgb(80, 134, 233);
    height: 3em;
    width: 13em;
    align-content: center;
    float: center;
    border-radius: 13px;
    color: white;
    font-weight: bold;
}
.middle input[type=submit]{
    background-color: rgb(43, 170, 43);
    height: 3em;
    width: 13em;
    align-content: center;
    float: center;
    border-radius: 13px;
    color: white;
    font-weight: bold;
}
.right input[type=submit]{
    background-color: orange;
    height: 3em;
    width: 13em;
    align-content: center;
    float: center;
    border-radius: 13px;
    color: white;
    font-weight: bold;
}
* {
  box-sizing: border-box;
}

/* Create three unequal columns that floats next to each other */
.column {
  float: left;
  padding-top: 140px;
  height: 300px; /* Should be removed. Only for demonstration */
}

.left {
  width: 42%;
  padding-left: 350px;
}
.right {
    width: 30%;
    padding-left: 5px;
}
.middle {
  width: 15%;
  padding-left: 5px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
<body>
    <div class="header">
        <h1>Railway Enquiry System </h1>
        </div>
        <div class="container-fluid">
        <div class="row1 row">
            <div class="col-lg-4">
                <!---<span class="sty" style="font-size:40px; color: yellow;"></span>-->
            </div>
            <div class="col-lg-6"></div>
            <!--<div class="col-lg-1"><span class="sty" style="font-size:17px;">Welcome:{{request.user}}</span></div>-->
           <!-- <div class="col-lg-1"><a href="logout"><button class="btn btn-danger">Log Out</button> </a></div>-->
        </div>
        <div class="row">
            <div class="column left">
                <a href="schedule"> <input type="submit" name="submit" value="Train Schedule">
            </div>
            <div class="column middle">
               <a href="search"><input type="submit" name="submit" value="Train Between Station">
            </div>
            <div class="column right">
              
               <a href="pnr"><input type="submit" name="submit" value="PNR Enquiry">
            </form>
              </div>

          </div>
          
    

    </body>

</html>


  
{% endblock %}

features/templates/features/pnr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PNR NUMBER</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}

   
    <style>
        body{
            background-image:url('{% static "images/pnr.jpeg"%}');
            background-size:100%;
            background-repeat:no-repeat;


        }
        .sty
        {
            font-family: 'Arial';
            color:white;
        }
        .hd
        {
            margin-left:400px;

            }
         .tform{
            background-color:rgba(0,0,0,0.3);
            }
            .fpnr
            {
                width:20%;
                margin-left:500px;
                margin-top:150px;
                padding:15px;
                background-color:rgba(0,0,0,0.3);
                }

        .tick{
            width:20%;
            height:150px;
           background-image:url('{% static "images/ticket6"%}');
            background-size:100% 100%;
            background-repeat:no-repeat;
            }
    </style>
</head>
<body>

{%if r%}
<h1 style="text-align:center;font-family:sans seriff; color: white; background-color: red; opacity: 70%; ">CURRENT PNR STATUS</h1><div class="fpnr">
{%for i in r%}

    <h4 class="sty">PNR-{{i.pnr}}<br/>
    NO of seats-{{i.nos}}<br/>
    Status-{{i.status}}<br/><br/></h4>

{%endfor%}
        <a href="{%url 'home:hom'%}"><button class="btn btn-success"style="background-color: purple">Back To Homepage</button></a>

</div>
{%else%}
<h1 style="text-align:center;font-family:sans seriff; color: white; background-color: red; opacity: 70%; ">ENTER PNR NUMBER</h1>

<form class="fpnr" action="" method="POST" style="background-color: red; opacity: 70%;">
    {%csrf_token%}
    <span class="sty">PASSENGER NAME RECORD: </span><input type="text" name="pnr" required=""><br/><br/>
    <center><input type="submit" class="btn btn-primary" value="Check"></center>
</form>
{%endif%}

features/templates/features/schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Train Schedule</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}

     <style>
        body{
            background-image:url('{% static "images/trai.jpg"%}');
            background-size:100%;
            background-opacity:0.4;
            background-repeat:no-repeat;


        }
        .sty
        {
            font-family: 'Arial', cursive;
            color:white;
        }
        .hd
        {
            margin-left:400px;

            }
         .tform{
            background-color:rgba(0,0,0,0.3);
            }



    </style>
</head>
<body>
    <div class="row">
        <div class="col-lg-4"></div>
    <div class="col-lg-4" style="background-color:darkslategray;margin-top:152px; opacity: 90%;margin-left: 320px;
margin-right: 357px;">
    <h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:Yellow;">Train Schedule</span></h2>

    <form class="form-inline" style="margin-top: 44px;margin-left: 94px;"action="trains">

        <span class="sty" style="font-size:30px;color: red;font-style: normal;">Select Train Number/Name:</span><br/><br/>
        <select name="tnum">
        {% for i in a %}
            <option value="{{i.tno}}">{{i.tno}}/{{i.tname}}</option>
        {%endfor%}
        </select>
        <input type="submit" class="btn btn-primary" value="check">
    </form>
        <br/>
        </div>
        </div>
</body>
</html>

features/templates/features/seat.html
{% extends 'features/srbase.html' %}

{% block body %}
    <h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:yellow;">Search Trains </span></h2>
    <br/><br/>
    
    <center><form class="form-inline" style="margin-left:200px;"action="trains" method="POST">
        {% csrf_token %}
        <span class="sty" style="font-size:30px;color:yellow;">From:</span><select name="src">
            {% for i in a %}
            <option value="{{i.sid}}">{{i.sname}}</option>
            {%endfor%}
        </select>
        <span class="sty" style="font-size:30px;color:yellow;">Destination:</span>
        <select name="des">
            {% for i in a %}
            <option value="{{i.sid}}">{{i.sname}}</option>
            {%endfor%}
        </select>
        &nbsp
        <input class="btn btn-primary" type="submit" value="Search">
    </form></center>
{% endblock%}

features/templates/features/srbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}

    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <style>
        body{
            background-image:url('{% static "images/neww.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;


        }
        .sty
        {
            font-family: 'Arial', cursive;
            color:white;
        }
        .hd
        {
            margin-left:400px;

            }
         .tform{
            background-color:rgba(0,0,0,0.3);
            }
            .fpnr
            {
                width:20%;
                margin-left:500px;
                margin-top:150px;
                padding:15px;
                background-color:rgba(0,0,0,0.3);
                }

        .tick{
            width:20%;
            height:150px;
            background-image:url('{% static "images/pnr.jpg"%}');
            background-size:100% 100%;
            background-repeat:no-repeat;
            }
    </style>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

features/templates/features/trains.html
{% extends 'features/srbase.html' %}
{%block body%}
{%csrf_token%}
<h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:brown;">Search Trains</span></h2>
    <br/>
    <br/>
    <br/>
    <center><form class="tform" action="book1/" method="POST" style="background-color: brown; opacity: 70%;padding: 14px;">
        {%csrf_token%}
        <div class="hd" style="margin-left: 0px;">
            <input type="text" value="{{src}}" name="src" readonly><span style="color: white;">======></span><input type="text" value="{{des}}" name="des" readonly><br/></br>
            <!--<b style="color: white;">DATE OF JOURNEY:</b> <input type="text" placeholder="DD/MM/YYYY" id="dt" name="date">--><br/>
        </div>
    <h1 id="123"></h1>
        <span hidden id="od">{{o}}</span>
  	<table style="margin-left:50px;font-size:20px;color:black;" class="table-striped table-bordered table-hover">
        <tr class="sty" style="color:black;padding:10px;">
           <th style="padding:10px;">Train Number</th>
            <th style="padding:10px;">Arrival Station</th>
            <th style="padding:10px;">Arrival Time</th>
            <th style="padding:10px;">Select Class</th>
            <th style="padding:10px;">Availibility</th>
            <!--<th style="padding:10px;">Seats</th>-->
            <th style="padding:10px;">No of Seats</th>
            <th style="padding:10px;">Book</th>
        </tr>

    {% for i in data %}
        <tr>
            <td style="padding:15px;"><h5 ><b>{{i.tno}}</b></h5></td>
             <td style="padding:15px;"><h5><b>{{i.sid}}<b/></h5></td>
            <td style="padding:15px;"><h5><b>{{i.atime}}</b></h5></td>
            <td><h6>
                <select id="{{i.tno}}" onchange="x(this.value,this.id)" name="cls{{i.tno}}">
                    <option value="NONE">NONE</option>
                    <option value="AC">AC</option>
                    <option value="2S">2S</option>
                    <option value="3A">3A</option>
                    <option value="SL">SL</option>
                </select>
            </h6></td>
            <td ><h6 id="{{i.tno}}1"></h6></td>
            <!--<td><input id="{{i.tno}}p1" type="text" name="price{{i.tno}}" value="" readonly > </h6></td>-->
            <td><input type="number" id="{{i.tno}}-2" name="nos{{i.tno}}"/></td>
            <td>
                <button type="submit" class="btn btn-success"  value="{{i.tno}}" name="bk">Book Seat</button>
            </td>
        </tr>

    {% endfor %}
    </table>

        <br/><br/><br/>
        </form></center>
  <script>
    function x(vl,z)
    {

        var da=document.getElementById('dt').value;
        var o=document.getElementById('od').innerHTML;
        $.ajax({
            type:'POST',
            url:'search/trains/cva/',
            data:{  tno:z,
                    cls:vl,
                    od:o,
                    dt:da,
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()

                  },
        success:function(data){
            var read=data.read;
            var price=data.price;
            $('#'+z+'1').html(data.read+" Seats");

            $('#'+z+'p1').val(price);
                               }
            }
                )
    }
      </script>
{% load static %}
 <style>
        body{
            background-image:url('{% static "images/neww.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;


        }
   <style>     
        {%endblock%} 

features/templates/features/trinfo.html
{% extends 'features/srbase.html' %}
{% block body%}
<h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:black;">Train Schedule</span></h2>

    <table style="margin:100px 500px;font-size:30px;color:black;" class="table-striped table-bordered table-hover">
        <tr class="sty" style="color:black;padding:10px;">
           <th style="padding:10px;">Station ID</th>

            <th style="padding:10px;">Arrival Time</th>
        </tr>

    {% for i in data %}
        <tr>
            <td><h4>{{i.sid}}</h4> </td>
            <td><h4>{{i.atime}}</h4></td>
        </tr>

    {% endfor %}

    </table>
    <a href="{%url 'home:hom'%}" style="margin-left:550px"><button class="btn btn-primary">Back To Homepage</button></a>
{% endblock%}